services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - mongo-net

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
