version: '3'

services:
  web:
    build: ./app
    ports:
      - "4000:4000"
    depends_on:
      - elasticsearch
    networks:
      - es-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
