version: "3.8"

services:
  web:
    build: ./app
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
